### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.servicefabric.models.error_model_py3.ErrorModel
  - azure.mgmt.servicefabric.models.error_model_py3.ErrorModelException
  fullName: azure.mgmt.servicefabric.models.error_model_py3
  langs:
  - python
  module: azure.mgmt.servicefabric.models.error_model_py3
  name: error_model_py3
  source:
    id: error_model_py3
    path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\error_model_py3.py
    remote:
      branch: northstar
      path: azure-mgmt-servicefabric\azure\mgmt\servicefabric\models\error_model_py3.py
      repo: https://github.com/mmacy/azure-sdk-for-python
    startLine: 0
  type: module
  uid: azure.mgmt.servicefabric.models.error_model_py3
references:
- fullName: azure.mgmt.servicefabric.models.error_model_py3.ErrorModel
  isExternal: false
  name: ErrorModel
  parent: azure.mgmt.servicefabric.models.error_model_py3
  uid: azure.mgmt.servicefabric.models.error_model_py3.ErrorModel
- fullName: azure.mgmt.servicefabric.models.error_model_py3.ErrorModelException
  isExternal: false
  name: ErrorModelException
  parent: azure.mgmt.servicefabric.models.error_model_py3
  uid: azure.mgmt.servicefabric.models.error_model_py3.ErrorModelException
